apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
- ../../resources
images:
- name: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/ejl-repo
  newName: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/ejl-repo
  newTag: 17b8a0d935a59c7b65711919b31aeb2508fc7e15
