apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources
images:
- name: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/ejl-repo
  newName: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/ejl-repo
  newTag: 80819743bff8655cc0e716a0989908e8c41cce07
