apiVersion: v1
kind: Service
metadata:
  name: sb-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: spring
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/ejl-repo:c444789308949fa50a3e02365db583e31511daa5