apiVersion: v1
kind: Service
metadata:
  name: sb-svc
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: spring
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: 236747833953.dkr.ecr.ap-northeast-2.amazonaws.com/lee-repo:c85cccc34dd2a150fad4f88e85f9e6da3bfada4c
      imagePullSecrets:
        - name: regcred
